[package]
name = "sui_magical_garden"
edition = "2024.beta" 
license = "MIT"
authors = ["Daniela Silvana Tochi danielastochi@gmail.com"]


[dependencies]

[addresses]
sui_magical_garden = "0x0"

[dev-dependencies]

[dev-addresses]

